site_name: ez_visual_regression

nav:
    - About: index.md
    - Getting Started: getting_started.md

theme:
  name: material

repo_url: https://github.com/Descent098/ez-visual-regression


site_description: Used to take screenshots with selenium (pages or elements) and compare to baseline

site_author: Kieran Wood
